### ISSUE TITLE
setUpClass() missing 2 required positional arguments: 'app' and 'client'

### ISSUE THREAD

**Issue by richardkhonan0797** [TotallyNotChase/flask-unittest#1]
```
conftest.py

class TestBase(flask_unittest.AppClientTestCase):
def create_app(self):
    app = init_app('test', config)
    ctx = app.app_context()
    ctx.push()
    yield app
    ctx.pop()
```

```
test_signup.py

from app import db
from app.tests.conftest import TestBase
from app.tests.fixtures.seed_fixture_country_code import seed_fixture_country_code

class TestSignup(TestBase):
@classmethod
def setUpClass(cls, app, client):
    db.create_all()

@classmethod
def tearDownClass(cls, app, client):
    db.session.remove()
    db.drop_all()

def setUp(self, app, client):
    # db.create_all()
    seed_fixture_country_code()

def tearDown(self, app, client):
    pass

def test_signin(self, app, client):
    response = client.post(
        "/signup",
        json={
            "email": "unit@test.com",
            "firstname": "Unit",
            "lastname": "Test",
            "password": "secret",
            "country_code_contact_number": "62",
            "contact_number": "12345678",
            "country": "Indonesia",
            "postalCode": "1111",
            "birthday": "1990-01-01",
            "gender": "Male",
            "token_issuer_server": "ID"
        },
        headers={
            "api-key": "user",
            "User-Agent": "test"
        }
    )
    res_json = response.get_json()
    self.assertEqual(201, response.status_code)
    self.assertIn("access_token", res_json["data"])
    self.assertEqual("Unit", res_json["data"]["user"]["firstname"])
    self.assertEqual("Test", res_json["data"]["user"]["lastname"])
```

Hi, how can I fix this? I got setUpClass() missing 2 required positional arguments: 'app' and 'client' each time I run the test.

**Comment by TotallyNotChase** [comment]
The class methods in testcases do not have access to the extra arguments provided by `AppClientTestCase` (or any other test case included in this library).

Unfortunately, due to how unittest itself is designed - your app is only created *after* instantiation of your class. This means that class methods (static side methods) cannot have access to the app (which only exists at instance side). There is nothing that can be done regarding this as I cannot hijack unittest's own execution pattern. Well, at least that wouldn't be very clean and ideal.

The methods that do have access to the resources provided by the `flask_unittest` testcases are mentioned in the docs. Specifically, your `setUp`, `tearDown` and all test methods can have access to these extra resources - as these are all invoked after instantiating the class.

**Comment by TotallyNotChase** [comment]
Given your usecase, I do not think you actually need the extra resources in your class methods. Do note however that `create_app` is called for each **test set** (setUp, test, tearDown) - and hence the application/client is created per test set. This ensures all test sets are independent from each other and is considered good practice. This also means that you may put app specific setup in `create_app` itself - which will be executed for **each test set** (not per class).

**Comment by richardkhonan0797** [comment]
Thank you for explaining. So let's say that I have 3 tests in the `TestSignup` class. Is it possible to just `create_app` once? So that I can use the same app and db session until all the tests finished.
